
# Site settings
title: Jingpeng Hong (洪景鹏)
name: Jingpeng Hong
email: jphong@uchicago.edu
baseurl: ""
url: "https://jingpenghong.github.io/"
github_username:  JingpengHong
disqus_baseurl: "https://jingpenghong.github.io/"
disqus_shortname: https-jingpenghong-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jingpeng Hong"